module.exports = {
    name: "roast",
    aliases: ["Roast", "ROAST", " roast", " Roast", " ROAST"],
    usage: ["[@alguém]"],
    description: "Dás um roast a alguém",
    clientPermissions: ["SEND_MESSAGES"],
    userPermissions: [],
    run: async (client, message, args) => {
        let userArray = message.content.split(" ");
        let userArgs = userArray.slice(1);
        let member = message.mentions.members.first() || message.guild.members.cache.get(userArgs[0]) || message.guild.members.cache.find(x => x.user.username.toLowerCase() === userArgs.slice(0).join(" ") || x.user.username === userArgs[0]) || message.member;
        const messages = [
            `You all know ${member.user}\’s is my first and most longtime friend I have. What you may not know is that he’s also the first and most longtime customer of ProActive Acne Systems. `, `Good lord this is an ugly group of people. Holy shit, you know the crowd is ugly when we invited ${member.user}\’s as eye candy. `, `And ${member.user}\’s you’re looking pretty rough this evening. ${member.user} looks like if sweatpants were a person. `,
            `Getting married to you must’ve been rough. What was your wedding song? “How Much Is That Doggy In The Window?” `, `${member.user}\’s is so ugly he’s been the only one ever rejected from Queer Eye for the Straight guy. `, `${member.user}\’s is so ugly in October when he went to the haunted house they handed his an application. `,
            `${member.user}\’s psychiatrist said he was crazy and he said he wanted a second opinion. The psychiatrist said “Okay, you’re ugly too.” `, `${member.user}\’s nose is so big he Apple had to make a custom iPhone that unlocks using Nose ID. `, `${member.user} when are you gonna buy a new outfit?? `, `Everyday you wear the same jeans and same flannel patterned shirt. You’re like if Al Borland from Home Improvement learned to program a computer.`,
            `The way ${member.user} dresses looks like the first half of a commercial for antidepressants. `, `${member.user} is actually pretty good looking, but has a boring personality. Good looks but boring personality, you’re like real life clickbait.`, `${member.user} has worn the same outfit for like 10 years. Holy shit….the only person who’s worn the same clothes longer than you is Bart Simpson. `, `${member.user} I’m glad you and your dull personality could be here. I’m excited to hear your speech at the wedding. With your personality, I’m sure your speech will combine the thrill of talking, with the excitement of standing there. `, `${member.user}\'s outfit was recently featured on the cover of Yawn Magazine. `,
            `We are doing this roast tonight to help ${member.user} live out one of his sexual fantasies, to have a room full of his friends shit all over him. `, `A little known fact is that a long time ago ${member.user} used to work at McDonald’s. It was the last time anyone said about your work, “I’m lovin’ it.” `, `This is exciting ${member.user} right?? Well tell your face. `, `${member.user} if laughter is the best medicine, your face must be curing the world. `, `It’s nice to see such a diverse crowd here today. We’ve got Indians, Jews, Whites, and whatever the fuck ${member.user} is.`, `But ${member.user} you’re really looking good nowadays. What he has lost in weight, he has also GAINED in weight.`,
            `${member.user} I checked your Facebook, and it turns out you used to be a bit chubby. I’m impressed that you’ve managed to lose so much weight. That’s right, he lost 30 pounds on Nutrisystem, and another 10 when he shaved his back.`, `${member.user} you're so fat and lazy the only exercise he gets is when his Restless Leg Syndrome starts flaring up.`, `${member.user} you look like if the fat kid from Stranger Things wished he was big.`, `The church didn’t accept ${member.user}\'s gay lifestyle. So he started his own religion: The Church of Latter Day Taints. It’s like a normal church, except you’re happy when the priest fucks you.`,
            `Me and ${member.user} are really good friends but we’ve had our ups and downs, one time he actually tried to sue me for $10,000. I got really defensive and was like “You’re suing me for $10,000?? Fuck you…you can suck my dick.” and he was like, “well OK if you want to settle out of court.”`, `When I heard that ${member.user} finally came out of the closet I wasn’t really surprised….dude you’re so gay MY ass hurts.`, `I once asked ${member.user} why he dresses so flamboyantly and he got upset and hit me with his purse.`, `Backstage before this speech I rolled a gigantic fatty. Because that was the only way we could get ${member.user} on to the stage.`]
        const randomMessage = messages[Math.floor(Math.random() * messages.length)];
        message.channel.send(randomMessage)
    }
}